### ISSUE TITLE
The girl is 12' 6" tall

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#30]
We changed the units to meters, but didn't adjust the size of the artwork.  From the picture in https://github.com/phetsims/center-and-spread/issues/29#issue-1138655420, I estimated that the girl is around 12 feet 6 inches tall.

@arouinfar can you please advise?

**Comment by samreid** [comment]
Also, the ball is measured at 63cm diameter, but should be around 22cm diameter (if it were to scale).

**Comment by arouinfar** [comment]
I'm guessing this was a mis-tag, but sims that switch between units for localization reasons (such as Unit Rates switching between kg and lbs) don't actually convert values. Not sure if that is at all relevant to this sim, but there is precedent elsewhere for simply treating the unit as a label.

**Comment by samreid** [comment]
Sorry for the mis-tag!

**Comment by amanda-phet** [comment]
Ideas that were discussed in 2/16/22: 
- keep it the same, since this is something people might not notice
- reduce the scale of the person and ball to be more appropriate
- change the units to feet (but a translator could still make it meters) 
- remove units 

We decided to keep it as-is for now. If a student notices the scaling, that's great reasoning on their part! But we are ok with the scale being unrealistic since it's important to include units, and it's important that they are metric.
