### ISSUE TITLE
Should the cursor be a hand or left-right arrow for the cards?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#31]
Should the cursor be a hand or left-right arrow for the cards?  It's currently a hand but we can make it be a left-right arrow if that's preferable.  It can only drag left and right, so that seems reasonable, but also the hand seems like a natural default.

**Comment by amanda-phet** [comment]
Discussed 2/16/22: 

- there is a precedent for using an arrow cursor for some things (Geometric Optics, Neuron, Make a Ten) to distinguish an interaction
- The hand is a dramatic change from an arrow, and the arrow cursor is kind of small, so the hand offers more contrast
- hand is kind of inviting 
- If students really struggle with the left-right action, it might be worth considering the arrow cursor 
- Since one of Sam's family members clicked the card and didn't drag it, it might have been clearer if the cursor was a left-right arrow 

Let's wait on #29 and see if that improves the interaction for this part of the sim. I will also make a note to look for this in interviews!
