### ISSUE TITLE
Float accordion box to stay right below the question bar

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#50]
@amanda-phet feel to adjust priority if you would like.

**Comment by samreid** [comment]
To me, this sim seems like we should just use the dev bounds.  If we float things to the top or side in portrait, things will get very far away and it will seem awkward.  

@chrisklus says: Using some of that vertical height in portrait could make it so we don't need to have soccer balls go behind the accordion box.  It feels more natural for phone layout and I'm not worried about things being far away because phones are naturally small.

In this conversation, we mocked up this prototype (in photoshop) to get a sense of this proposal, that some of us like and some don't like.  Sorry about the copy/paste sky gradient.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/679486/155900482-e12b08d6-774c-4b32-96a6-428deafb3e55.png">

@amanda-phet can you please advise?

**Comment by amanda-phet** [comment]
This is what I thought we were imagining in a narrow scenario:
![image](https://user-images.githubusercontent.com/7852916/156003315-759e255e-bcee-48da-8119-859138d6cbef.png)

So, lots of sky, not lots of grass. Is this possible to do?

**Comment by chrisklus** [comment]
Yes, that's what I remember as well. I'd like to try it out before considering a different direction.

**Comment by samreid** [comment]
I implemented the floating layout and it is ready for review.

**Comment by samreid** [comment]
@chrisklus and I reviewed, will follow up on the TODO separately.  Closing.

**Comment by amanda-phet** [comment]
Looks good!
