### ISSUE TITLE
Design meeting requests from February 16 and before

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#51]
Immediate dev work:

- [x] #54

Remaining design considerations that have no current action items:

Should the cards get a visual indicator like the balls, such as an orange stroke around them? 
There are other visual indicators on cards, so we’d want to make sure it all works together

Accordion box is currently looking large on Median screen 
Waiting to see how large this is after other screens have features

Should predict checkboxes be closer to the grass? 

Info button: Should the Mean & Median screen have an info button to describe how mean is calculated? 
This might be nice

Outlier button to highlight outlier?

@amanda-phet please promote any of the above questions from design meeting to checkboxes for @samreid and I to complete if you have suggestions to try, or their own issue. And please update priority as appropriate. Thanks!

**Comment by amanda-phet** [comment]
The only thing here that I think is worthy of more consideration is the info button to describe mean/median calculations. We have more info buttons coming, so I would like to think about this, because I don't have a design for an info button for this screen. I have added it to my math sim brainstorming agenda and will open an issue when I'm ready with a design.
